[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]

[lib]
name = "kvproto"

[features]
default = []
link-sys = ["grpcio/link-sys"]

[dependencies]
protobuf = "1.*"
futures = "0.1"
grpcio = "0.1"
