[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]

[lib]
name = "kvproto"

[dependencies]
protobuf = "1.2"

[dependencies.grpc]
git = "https://github.com/pingcap/grpc-rs.git"
features = ["static-link"]
