[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]

[lib]
name = "kvproto"

[dependencies]
protobuf = "1.2"
futures = "0.1"
futures-cpupool = "0.1"

[dependencies.grpc]
git = "https://github.com/stepancheg/grpc-rust.git"
