[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]

[lib]
name = "kvproto"

[dependencies]
protobuf = "1.*"
futures = "0.1"
grpcio = "0.2"
raft = { git = "https://github.com/pingcap/raft-rs.git", branch = "context" }
