[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]

[lib]
name = "kvproto"

[dependencies]
protobuf = "1.*"
futures = "0.1"
futures-cpupool = "0.1"

[dependencies.grpc]
git = "https://github.com/stepancheg/grpc-rust.git"
rev = "13bdc724e5d9467792b289df822c2479812a9808"

