[package]
name = "kvproto"
version = "0.0.2"
keywords = ["TiKV"]
edition = "2018"
build = "build.rs"

[lib]
name = "kvproto"
path = "src/lib.rs"

[features]
default = ["protobuf-codec"]
protobuf-codec = ["protobuf-build/grpcio-protobuf-codec", "raft-proto/protobuf-codec", "grpcio/protobuf-codec"]
prost-codec = ["prost", "prost-derive", "bytes", "lazy_static", "protobuf-build/grpcio-prost-codec", "raft-proto/prost-codec", "grpcio/prost-codec"]

[dependencies]
protobuf = "2"
prost = { version = "0.5", optional = true }
prost-derive = { version = "0.5", optional = true }
bytes = { version = "0.4", optional = true }
futures = "0.1"
grpcio = { version = "0.5.0-alpha.2", default-features = false, features = ["secure"] }
raft-proto = { git = "https://github.com/pingcap/raft-rs.git", rev = "1377cb6c9002f9fca0f2eca2bbff4c2cbc9d38b5", default-features = false }
lazy_static = { version = "1.3", optional = true }

[build-dependencies]
protobuf-build = { git = "https://github.com/tikv/protobuf-build.git", rev = "54c089895e4bf42481c2af46ebf73295c0e5d6b9", default-features = false }
