[package]
name = "kvproto"
version = "0.0.2"
keywords = ["TiKV"]
edition = "2018"
build = "build.rs"

[lib]
name = "kvproto"
path = "src/lib.rs"

[features]
gen = []

[dependencies]
prost = { git = "https://github.com/danburkert/prost", rev = "1944c27c3029d01ff216e7b126d846b6cf8c7d77" }
prost-derive = { git = "https://github.com/danburkert/prost", rev = "1944c27c3029d01ff216e7b126d846b6cf8c7d77" }
bytes = "0.4"
futures = "0.1"
grpcio = { version = "0.5.0-alpha.1", features = ["prost-codec"] }
raft-proto = { git = "https://github.com/pingcap/raft-rs", rev = "07cde2d752330a54c9ba33033b1a0982bfd2e10d" }
lazy_static = "1.3"

[build-dependencies]
protobuf-build = "0.6.3"

[replace]
"prost:0.5.0" = { git = "https://github.com/danburkert/prost", rev = "1944c27c3029d01ff216e7b126d846b6cf8c7d77" }
