required = ["github.com/gogo/protobuf/protoc-gen-gofast","golang.org/x/tools/cmd/goimports"]


[[constraint]]
  name = "google.golang.org/grpc"
  source = "https://github.com/grpc/grpc-go.git"
  version = "= v1.12.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  source = "https://github.com/gogo/protobuf.git"
  version = "= 1.1.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  source = "https://github.com/golang/protobuf.git"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true
