// Code generated by protoc-gen-go.
// source: msgpb.proto
// DO NOT EDIT!

/*
Package msgpb is a generated protocol buffer package.

It is generated from these files:
	msgpb.proto

It has these top-level messages:
	Message
*/
package msgpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import raft_cmdpb "github.com/pingcap/kvproto/pkg/raft_cmdpb"
import raft_serverpb "github.com/pingcap/kvproto/pkg/raft_serverpb"
import kvrpcpb "github.com/pingcap/kvproto/pkg/kvrpcpb"
import coprocessor "github.com/pingcap/kvproto/pkg/coprocessor"
import pdpb "github.com/pingcap/kvproto/pkg/pdpb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MessageType int32

const (
	MessageType_None     MessageType = 0
	MessageType_Cmd      MessageType = 1
	MessageType_CmdResp  MessageType = 2
	MessageType_Raft     MessageType = 3
	MessageType_KvReq    MessageType = 4
	MessageType_KvResp   MessageType = 5
	MessageType_CopReq   MessageType = 6
	MessageType_CopResp  MessageType = 7
	MessageType_PdReq    MessageType = 8
	MessageType_PdResp   MessageType = 9
	MessageType_Snapshot MessageType = 10
)

var MessageType_name = map[int32]string{
	0:  "None",
	1:  "Cmd",
	2:  "CmdResp",
	3:  "Raft",
	4:  "KvReq",
	5:  "KvResp",
	6:  "CopReq",
	7:  "CopResp",
	8:  "PdReq",
	9:  "PdResp",
	10: "Snapshot",
}
var MessageType_value = map[string]int32{
	"None":     0,
	"Cmd":      1,
	"CmdResp":  2,
	"Raft":     3,
	"KvReq":    4,
	"KvResp":   5,
	"CopReq":   6,
	"CopResp":  7,
	"PdReq":    8,
	"PdResp":   9,
	"Snapshot": 10,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Message holds all messages communicating with TiKV.
type Message struct {
	MsgType          *MessageType                `protobuf:"varint,1,opt,name=msg_type,enum=msgpb.MessageType" json:"msg_type,omitempty"`
	CmdReq           *raft_cmdpb.RaftCmdRequest  `protobuf:"bytes,2,opt,name=cmd_req" json:"cmd_req,omitempty"`
	CmdResp          *raft_cmdpb.RaftCmdResponse `protobuf:"bytes,3,opt,name=cmd_resp" json:"cmd_resp,omitempty"`
	Raft             *raft_serverpb.RaftMessage  `protobuf:"bytes,4,opt,name=raft" json:"raft,omitempty"`
	KvReq            *kvrpcpb.Request            `protobuf:"bytes,5,opt,name=kv_req" json:"kv_req,omitempty"`
	KvResp           *kvrpcpb.Response           `protobuf:"bytes,6,opt,name=kv_resp" json:"kv_resp,omitempty"`
	CopReq           *coprocessor.Request        `protobuf:"bytes,7,opt,name=cop_req" json:"cop_req,omitempty"`
	CopResp          *coprocessor.Response       `protobuf:"bytes,8,opt,name=cop_resp" json:"cop_resp,omitempty"`
	PdReq            *pdpb.Request               `protobuf:"bytes,9,opt,name=pd_req" json:"pd_req,omitempty"`
	PdResp           *pdpb.Response              `protobuf:"bytes,10,opt,name=pd_resp" json:"pd_resp,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetMsgType() MessageType {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return MessageType_None
}

func (m *Message) GetCmdReq() *raft_cmdpb.RaftCmdRequest {
	if m != nil {
		return m.CmdReq
	}
	return nil
}

func (m *Message) GetCmdResp() *raft_cmdpb.RaftCmdResponse {
	if m != nil {
		return m.CmdResp
	}
	return nil
}

func (m *Message) GetRaft() *raft_serverpb.RaftMessage {
	if m != nil {
		return m.Raft
	}
	return nil
}

func (m *Message) GetKvReq() *kvrpcpb.Request {
	if m != nil {
		return m.KvReq
	}
	return nil
}

func (m *Message) GetKvResp() *kvrpcpb.Response {
	if m != nil {
		return m.KvResp
	}
	return nil
}

func (m *Message) GetCopReq() *coprocessor.Request {
	if m != nil {
		return m.CopReq
	}
	return nil
}

func (m *Message) GetCopResp() *coprocessor.Response {
	if m != nil {
		return m.CopResp
	}
	return nil
}

func (m *Message) GetPdReq() *pdpb.Request {
	if m != nil {
		return m.PdReq
	}
	return nil
}

func (m *Message) GetPdResp() *pdpb.Response {
	if m != nil {
		return m.PdResp
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "msgpb.Message")
	proto.RegisterEnum("msgpb.MessageType", MessageType_name, MessageType_value)
}

var fileDescriptor0 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0xdf, 0x4a, 0xeb, 0x40,
	0x10, 0xc6, 0x4f, 0x9a, 0x3f, 0x9b, 0x4e, 0x4e, 0xcb, 0x76, 0xcf, 0x39, 0x10, 0x7a, 0x10, 0x4b,
	0x51, 0x2c, 0x8a, 0xb9, 0xe8, 0x2b, 0xf4, 0x52, 0x94, 0x52, 0xbd, 0x2f, 0x35, 0x5d, 0x2b, 0x94,
	0x76, 0xb7, 0xd9, 0x18, 0xf0, 0x19, 0xf4, 0xa1, 0x9d, 0x9d, 0x64, 0x43, 0x10, 0xef, 0x26, 0xf3,
	0xfd, 0xf6, 0x9b, 0x99, 0x2f, 0x90, 0x1c, 0xcc, 0x4e, 0x3f, 0x67, 0xba, 0x50, 0xa5, 0x12, 0x21,
	0x7d, 0x8c, 0x79, 0xb1, 0x79, 0x29, 0xd7, 0xf9, 0x61, 0xeb, 0x84, 0xf1, 0x1f, 0xea, 0x18, 0x59,
	0x54, 0xb2, 0x68, 0x9b, 0x83, 0x7d, 0x55, 0xe8, 0xbc, 0xfd, 0x1c, 0xe5, 0x0a, 0x8b, 0x5c, 0x1a,
	0xa3, 0x8a, 0xa6, 0x05, 0xba, 0xb5, 0x98, 0x7e, 0xf8, 0xc0, 0xee, 0x51, 0xdc, 0xec, 0xa4, 0xb8,
	0x80, 0x18, 0x27, 0xad, 0xcb, 0x77, 0x2d, 0x53, 0x6f, 0xe2, 0xcd, 0x86, 0x73, 0x91, 0xd5, 0x7b,
	0x34, 0xc4, 0x13, 0x2a, 0xe2, 0x06, 0x18, 0xee, 0xb0, 0x2e, 0xe4, 0x29, 0xed, 0x21, 0x94, 0xcc,
	0xc7, 0x59, 0x67, 0xb1, 0x15, 0x96, 0x8b, 0xc3, 0x76, 0x25, 0x4f, 0x6f, 0xd2, 0x94, 0xe2, 0x16,
	0xe2, 0x1a, 0x36, 0x3a, 0xf5, 0x89, 0xfe, 0xff, 0x23, 0x6d, 0xb4, 0x3a, 0x1a, 0x29, 0x66, 0x10,
	0x58, 0x35, 0x0d, 0xba, 0xc6, 0xed, 0x7d, 0x96, 0x76, 0xbb, 0x4e, 0x20, 0xda, 0x57, 0xb4, 0x44,
	0x48, 0x2c, 0xcf, 0xdc, 0xd9, 0x6e, 0xf4, 0x14, 0x18, 0x11, 0x38, 0x39, 0x22, 0x64, 0xd4, 0x41,
	0x9a, 0x79, 0x97, 0x78, 0x8b, 0xd2, 0x64, 0xc3, 0x88, 0xf9, 0x9b, 0x75, 0xe3, 0x72, 0x56, 0x57,
	0x78, 0x05, 0x61, 0xe8, 0x15, 0x13, 0xf7, 0xef, 0x1b, 0xd7, 0xf8, 0x9d, 0x41, 0xa4, 0xeb, 0x68,
	0xfa, 0x84, 0x0d, 0x32, 0x8a, 0xda, 0xf9, 0x9c, 0x03, 0xd3, 0x4d, 0x18, 0x40, 0xfa, 0xd0, 0xe9,
	0xf5, 0xfb, 0xeb, 0x4f, 0x0f, 0x92, 0x6e, 0xd6, 0x31, 0x04, 0x0f, 0xea, 0x28, 0xf9, 0x2f, 0xc1,
	0xc0, 0xc7, 0xa0, 0xb8, 0x27, 0x12, 0x60, 0x4d, 0x62, 0xbc, 0x67, 0x75, 0x1b, 0x0a, 0xf7, 0x45,
	0x1f, 0xc2, 0xbb, 0x0a, 0xe7, 0xf0, 0x40, 0x00, 0x44, 0xb6, 0x44, 0x20, 0xb4, 0xf5, 0x42, 0x69,
	0xdb, 0x8f, 0xe8, 0xa5, 0xad, 0x51, 0x60, 0x96, 0x5f, 0xda, 0xbf, 0xc4, 0x63, 0xcb, 0x2c, 0x6b,
	0xc3, 0xbe, 0xf8, 0x0d, 0xf1, 0xe3, 0x71, 0xa3, 0xcd, 0xab, 0x2a, 0x39, 0x7c, 0x05, 0x00, 0x00,
	0xff, 0xff, 0xb5, 0x9c, 0x4c, 0x90, 0x86, 0x02, 0x00, 0x00,
}
